export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const LOGIN_RESET = 'LOGIN_RESET'
export const LOGIN_AUTH = 'LOGIN_AUTH'
export const LOGIN_AUTH_SUCCESS = 'LOGIN_AUTH_SUCCESS'
export const LOGIN_AUTH_FAILURE = 'LOGIN_AUTH_FAILURE'
export const LOGIN_PASS_INVALID = 'LOGIN_PASS_INVALID'
